events {
    worker_connections 1024;
}

http {
    include /etc/nginx/conf.d/*.conf;

    server {
        listen 80;
        server_name localhost;

        location / {
            return 404 '{"error": "Environment not found"}';
            add_header Content-Type application/json;
        }
    }
}